version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20

  - package-ecosystem: "docker"
    directory: "/docker/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20

  - package-ecosystem: "docker"
    directory: "/docker/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20

  - package-ecosystem: "docker"
    directory: "/docker/nginx"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
